version: '2'

services:

  ui_build:
    hostname: ui_build
    build:
      context: ./mindcrunch
      dockerfile: docker/ui_build/Dockerfile
    ports:
    - 8080:8080
    volumes:
    - ./mindcrunch/ui:/ui

  phoenix:
    depends_on:
    - ui_build
    - tarantool
    hostname: phoenix
    build:
      context: ./mindcrunch
      dockerfile: docker/phoenix/Dockerfile
    ports:
    - 80:4000
    volumes:
    - ./mindcrunch/ui/dist:/mindcrunch/priv/static
    - ./mindcrunch/ui/dist/templates:/mindcrunch/lib/mindcrunch_web/templates/layout

  tarantool:
    build:
      context: ./mindcrunch
      dockerfile: docker/tarantool/Dockerfile
    hostname: tarantool
    ports:
    - 3301:3301
    environment:
    - TARANTOOL_USER_NAME=tarantool_client
    - TARANTOOL_USER_PASSWORD=password
